name: Deploy
on:
  workflow_run:
    workflows: ["Build and test"]
    types:
      - completed
jobs:
  deploy:
    strategy:
      matrix:
        node: [12.x, 14.x]
    runs-on: ubuntu-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact ${{ matrix.node }}
          path: dist
          retention-days: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/test-nodejs:${{ matrix.node}}

